package example.mybatis.entity;

import example.misc.Required;
import java.util.Date;

public class MstEmployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.cid
     *
     * @mbg.generated
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.eid
     *
     * @mbg.generated
     */
    private String eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.addr
     *
     * @mbg.generated
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.note
     *
     * @mbg.generated
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.created_timestamp
     *
     * @mbg.generated
     */
    private Date createdTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.created_userid
     *
     * @mbg.generated
     */
    private String createdUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.updated_timestamp
     *
     * @mbg.generated
     */
    private Date updatedTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.updated_userid
     *
     * @mbg.generated
     */
    private String updatedUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.test_dummy_col2
     *
     * @mbg.generated
     */
    @Required
    private String testDummyCol2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_employee.name_enc
     *
     * @mbg.generated
     */
    private byte[] nameEnc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.cid
     *
     * @return the value of mst_employee.cid
     *
     * @mbg.generated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.cid
     *
     * @param cid the value for mst_employee.cid
     *
     * @mbg.generated
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.eid
     *
     * @return the value of mst_employee.eid
     *
     * @mbg.generated
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.eid
     *
     * @param eid the value for mst_employee.eid
     *
     * @mbg.generated
     */
    public void setEid(String eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.name
     *
     * @return the value of mst_employee.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.name
     *
     * @param name the value for mst_employee.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.addr
     *
     * @return the value of mst_employee.addr
     *
     * @mbg.generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.addr
     *
     * @param addr the value for mst_employee.addr
     *
     * @mbg.generated
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.age
     *
     * @return the value of mst_employee.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.age
     *
     * @param age the value for mst_employee.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.note
     *
     * @return the value of mst_employee.note
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.note
     *
     * @param note the value for mst_employee.note
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.created_timestamp
     *
     * @return the value of mst_employee.created_timestamp
     *
     * @mbg.generated
     */
    public Date getCreatedTimestamp() {
        return createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.created_timestamp
     *
     * @param createdTimestamp the value for mst_employee.created_timestamp
     *
     * @mbg.generated
     */
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.created_userid
     *
     * @return the value of mst_employee.created_userid
     *
     * @mbg.generated
     */
    public String getCreatedUserid() {
        return createdUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.created_userid
     *
     * @param createdUserid the value for mst_employee.created_userid
     *
     * @mbg.generated
     */
    public void setCreatedUserid(String createdUserid) {
        this.createdUserid = createdUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.updated_timestamp
     *
     * @return the value of mst_employee.updated_timestamp
     *
     * @mbg.generated
     */
    public Date getUpdatedTimestamp() {
        return updatedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.updated_timestamp
     *
     * @param updatedTimestamp the value for mst_employee.updated_timestamp
     *
     * @mbg.generated
     */
    public void setUpdatedTimestamp(Date updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.updated_userid
     *
     * @return the value of mst_employee.updated_userid
     *
     * @mbg.generated
     */
    public String getUpdatedUserid() {
        return updatedUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.updated_userid
     *
     * @param updatedUserid the value for mst_employee.updated_userid
     *
     * @mbg.generated
     */
    public void setUpdatedUserid(String updatedUserid) {
        this.updatedUserid = updatedUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.version
     *
     * @return the value of mst_employee.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.version
     *
     * @param version the value for mst_employee.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.test_dummy_col2
     *
     * @return the value of mst_employee.test_dummy_col2
     *
     * @mbg.generated
     */
    public String getTestDummyCol2() {
        return testDummyCol2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.test_dummy_col2
     *
     * @param testDummyCol2 the value for mst_employee.test_dummy_col2
     *
     * @mbg.generated
     */
    public void setTestDummyCol2(String testDummyCol2) {
        this.testDummyCol2 = testDummyCol2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_employee.name_enc
     *
     * @return the value of mst_employee.name_enc
     *
     * @mbg.generated
     */
    public byte[] getNameEnc() {
        return nameEnc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_employee.name_enc
     *
     * @param nameEnc the value for mst_employee.name_enc
     *
     * @mbg.generated
     */
    public void setNameEnc(byte[] nameEnc) {
        this.nameEnc = nameEnc;
    }
}