package example.entity;

import java.util.Date;

public class MstCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_company.cid
     *
     * @mbg.generated
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_company.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_company.addr
     *
     * @mbg.generated
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_company.num_of_employee
     *
     * @mbg.generated
     */
    private Integer numOfEmployee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_company.created_timestamp
     *
     * @mbg.generated
     */
    private Date createdTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_company.created_userid
     *
     * @mbg.generated
     */
    private String createdUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_company.updated_timestamp
     *
     * @mbg.generated
     */
    private Date updatedTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_company.updated_userid
     *
     * @mbg.generated
     */
    private String updatedUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mst_company.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_company.cid
     *
     * @return the value of mst_company.cid
     *
     * @mbg.generated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_company.cid
     *
     * @param cid the value for mst_company.cid
     *
     * @mbg.generated
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_company.name
     *
     * @return the value of mst_company.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_company.name
     *
     * @param name the value for mst_company.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_company.addr
     *
     * @return the value of mst_company.addr
     *
     * @mbg.generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_company.addr
     *
     * @param addr the value for mst_company.addr
     *
     * @mbg.generated
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_company.num_of_employee
     *
     * @return the value of mst_company.num_of_employee
     *
     * @mbg.generated
     */
    public Integer getNumOfEmployee() {
        return numOfEmployee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_company.num_of_employee
     *
     * @param numOfEmployee the value for mst_company.num_of_employee
     *
     * @mbg.generated
     */
    public void setNumOfEmployee(Integer numOfEmployee) {
        this.numOfEmployee = numOfEmployee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_company.created_timestamp
     *
     * @return the value of mst_company.created_timestamp
     *
     * @mbg.generated
     */
    public Date getCreatedTimestamp() {
        return createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_company.created_timestamp
     *
     * @param createdTimestamp the value for mst_company.created_timestamp
     *
     * @mbg.generated
     */
    public void setCreatedTimestamp(Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_company.created_userid
     *
     * @return the value of mst_company.created_userid
     *
     * @mbg.generated
     */
    public String getCreatedUserid() {
        return createdUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_company.created_userid
     *
     * @param createdUserid the value for mst_company.created_userid
     *
     * @mbg.generated
     */
    public void setCreatedUserid(String createdUserid) {
        this.createdUserid = createdUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_company.updated_timestamp
     *
     * @return the value of mst_company.updated_timestamp
     *
     * @mbg.generated
     */
    public Date getUpdatedTimestamp() {
        return updatedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_company.updated_timestamp
     *
     * @param updatedTimestamp the value for mst_company.updated_timestamp
     *
     * @mbg.generated
     */
    public void setUpdatedTimestamp(Date updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_company.updated_userid
     *
     * @return the value of mst_company.updated_userid
     *
     * @mbg.generated
     */
    public String getUpdatedUserid() {
        return updatedUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_company.updated_userid
     *
     * @param updatedUserid the value for mst_company.updated_userid
     *
     * @mbg.generated
     */
    public void setUpdatedUserid(String updatedUserid) {
        this.updatedUserid = updatedUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mst_company.version
     *
     * @return the value of mst_company.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mst_company.version
     *
     * @param version the value for mst_company.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}